In [23]:
import numpy as np

In [2]:
dir(np)
len(dir(np))

532

In [3]:
# array is used to create 1D,2D,3D,4D,... data
# shape shows how many roows and columns
# size gives the no of values in the data
# ndim is used to find the dimention of the data
a=np.array([10,20,30,40,50,60])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[10 20 30 40 50 60]
(6,)
6
1


In [4]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
# arange is used to generate only 1D data
b=np.arange(11,19)
print(b)

[11 12 13 14 15 16 17 18]


In [6]:
# reshape is used to convert 1D to 2D,3D,....
b=np.arange(11,19)
print(b)
print('-------------------------')
c=b.reshape(2,4)
print(c)

[11 12 13 14 15 16 17 18]
-------------------------
[[11 12 13 14]
 [15 16 17 18]]


In [7]:
# reshape is use to conver from 1D to 2D only
# (-1,1) is one column
# (1,-1) is one row
a=np.array([10,11,12,13,14,15])
print(a)
print('--------------------')
b=a.reshape(-1,1)
print(b)
print('--------------------')
c=a.reshape(1,-1)
print(c)

[10 11 12 13 14 15]
--------------------
[[10]
 [11]
 [12]
 [13]
 [14]
 [15]]
--------------------
[[10 11 12 13 14 15]]


In [8]:
# zeros gives the o's data --> it meand black image
a=np.zeros((4,3),dtype=np.int32)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [9]:
# ones is used to give 1's data
a=np.ones((4,3),dtype=np.int64)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
#full is used to get data with our custom value
a=np.full((4,3),5)
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [11]:
# eye is used to get diagonal 1's and remaining 0's
a=np.eye(3,dtype=int,k=1)
print(a)

[[0 1 0]
 [0 0 1]
 [0 0 0]]


In [12]:
# ravel is used to convert any dimentional into 1D

a=np.array([[1,2,3,4],[1,5,6,7],[9,0,8,7]])
print(a)
print('---------------')
b=np.ravel(a)
print(b)

[[1 2 3 4]
 [1 5 6 7]
 [9 0 8 7]]
---------------
[1 2 3 4 1 5 6 7 9 0 8 7]


In [13]:
# Transpose is used to convert rows to column and column to row

a=np.array([[1,2,3,4],[1,5,6,7],[9,0,8,7]])
print(a)
print('--------------')
b=np.transpose(a)
print(b)

[[1 2 3 4]
 [1 5 6 7]
 [9 0 8 7]]
--------------
[[1 1 9]
 [2 5 0]
 [3 6 8]
 [4 7 7]]


In [14]:
# Concatination is used to merging the data
a=np.array([[10,11],[12,13]])
b=np.array([[100,200],[300,400]])
c=np.concatenate((a,b))
print(c)

[[ 10  11]
 [ 12  13]
 [100 200]
 [300 400]]


In [15]:
# randint is used to generate an integer randomly
a=np.random.randint(10,50,3)
print(a)

[30 13 14]


In [16]:
# randn it will generate data randomly b/w -3 to 3 by just taking no of col & rows
a=np.random.randn(5,4)
print(a)

[[ 0.05660722 -0.03835782 -0.76494006  0.84110457]
 [-0.34957955  0.52504022  0.83103382 -1.19246277]
 [ 0.90710118 -1.36321066  0.29171844 -0.80212453]
 [ 0.57545817 -2.16671299  0.09028036  0.04411338]
 [ 2.41110518 -0.58462132 -1.19123241 -0.5423002 ]]


In [17]:
#rand it will generate data randomly b/w 0 to 1 by just taking no of col & rows
a=np.random.rand(5,4)
print(a)

[[0.709338   0.46325416 0.52856214 0.67416905]
 [0.67227846 0.66714912 0.03453334 0.02066984]
 [0.02737472 0.83814135 0.74766656 0.28384817]
 [0.97201407 0.44099391 0.74662289 0.91944632]
 [0.85892322 0.99792067 0.06906599 0.4659691 ]]


In [18]:
 # axis=1 it is a row
 # axis=0 it is a column
a=np.array([[1,2,3,4],[1,5,6,7],[9,0,8,7]])
print(a)
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.sum(a,axis=1))
print(np.min(a,axis=1))
print(np.max(a,axis=1))

[[1 2 3 4]
 [1 5 6 7]
 [9 0 8 7]]
53
0
9
[10 19 24]
[1 1 0]
[4 7 9]


In [19]:
# argmax,argmin gives the index insted of value
a=np.array([[1,2,3,4],[1,5,6,7],[9,0,8,7]])
print(a)
print(np.argmin(a,axis=1))
print(np.argmax(a,axis=1))

[[1 2 3 4]
 [1 5 6 7]
 [9 0 8 7]]
[0 0 1]
[3 3 0]


In [20]:
# mat operations
a=np.array([[10,11],[12,13]])
b=np.array([[100,200],[300,400]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.matmul(a,b))
print(np.mod(a,b))

[[110 211]
 [312 413]]
[[ -90 -189]
 [-288 -387]]
[[4300 6400]
 [5100 7600]]
[[10 11]
 [12 13]]


In [21]:
# repeat to repeat the given values either in row or column
a=np.arange(11,16)
b=a.reshape(1,-1)
c=np.repeat(b,3,axis=0)
print(c)
print('------------------')
b=a.reshape(-1,1)
c=np.repeat(b,2,axis=1)
print(c)

[[11 12 13 14 15]
 [11 12 13 14 15]
 [11 12 13 14 15]]
------------------
[[11 11]
 [12 12]
 [13 13]
 [14 14]
 [15 15]]


In [29]:
# linespace is used to create data i.e evenly seperaes values
a=np.linspace(10,30,9,dtype=int)
print(a)

[10 12 15 17 20 22 25 27 30]


In [31]:
# range is used to maintail the spacelimit
print(list(range(1,20,2)))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [34]:
a=64
print(np.sqrt(a))
print(np.cos(a))
print(np.sin(a))

8.0
0.39185723042955
0.9200260381967906


In [35]:
a=np.array([[10,11],[12,13]])
b=np.array([[100,200],[300,400]])
np.vstack((a,b))

array([[ 10,  11],
       [ 12,  13],
       [100, 200],
       [300, 400]])

In [36]:
np.hstack((a,b))

array([[ 10,  11, 100, 200],
       [ 12,  13, 300, 400]])

In [37]:
np.exp(a)

array([[ 22026.46579481,  59874.1417152 ],
       [162754.791419  , 442413.39200892]])

In [43]:
aa=np.array(a)
aa.sort()

array([[10, 11],
       [12, 13]])